name: Test-Build
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
        continue-on-error: true

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

      - name: Sleep before deploy
        run: sleep 10
    
    #  - name: Deploy API Reports
    #    uses: peaceiris/actions-gh-pages@v3
    #    with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}
    #      publish_dir: ./testResults
  deploy:
    needs: test-api
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './testResults'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2